const SET_POST = "SET_POST";
const SET_COMMENT = "SET_COMMENT"
const RESET_INITIALE_LOAD = "RESET_INITIALE_LOAD"
const SET_NEW_POST = "SET_NEW_POST"
const TURN_ON_NEW_POST = "TURN_ON_NEW_POST"
const TURN_OFF_NEW_POST = "TURN_OFF_NEW_POST"
const RESET_NEW_POSTS = "RESET_NEW_POSTS"
const ADD_NEW_LIKE_TO_POST = "ADD_NEW_LIKE_TO_POST"
const REMOVE_LIKE_FROM_POST = "REMOVE_LIKE_FROM_POST"
const ADD_NEW_COMMENT_TO_POST = "ADD_NEW_COMMENT_TO_POST"



export default { SET_POST, SET_COMMENT, RESET_INITIALE_LOAD, 
  SET_NEW_POST, TURN_ON_NEW_POST, TURN_OFF_NEW_POST, 
  RESET_NEW_POSTS, ADD_NEW_LIKE_TO_POST,REMOVE_LIKE_FROM_POST, 
  ADD_NEW_COMMENT_TO_POST }